// Mocks generated by Mockito 5.2.0 from annotations
// in clean_architech/test/data/repository/weather_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:clean_architech/data/datasources/weather_local_data_source.dart'
    as _i2;
import 'package:clean_architech/data/datasources/weather_remote_data_source.dart'
    as _i5;
import 'package:clean_architech/data/models/weather_model.dart' as _i4;
import 'package:clean_architech/platform/network_info.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [WeatherLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherLocalDataSource extends _i1.Mock
    implements _i2.WeatherLocalDataSource {
  MockWeatherLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.WeatherModel?> getLastWeather(String? cityName) =>
      (super.noSuchMethod(Invocation.method(#getLastWeather, [cityName]),
              returnValue: Future<_i4.WeatherModel?>.value())
          as _i3.Future<_i4.WeatherModel?>);
  @override
  _i3.Future<void> cacheWeather(_i4.WeatherModel? weather) =>
      (super.noSuchMethod(Invocation.method(#cacheWeather, [weather]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}

/// A class which mocks [WeatherRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSource extends _i1.Mock
    implements _i5.WeatherRemoteDataSource {
  MockWeatherRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.WeatherModel?> getCurrentWeather(String? city) =>
      (super.noSuchMethod(Invocation.method(#getCurrentWeather, [city]),
              returnValue: Future<_i4.WeatherModel?>.value())
          as _i3.Future<_i4.WeatherModel?>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}
